#!/usr/bin/env python3

import requests
import json
import sys

endereco_servidor = 'http://127.0.0.1:5000/Tarefa/'

#lista = {1:"A", 2:"B", 3:"C"}
#first_arg = sys.argv[2]
#second_arg = sys.argv[3]

def adicionar(word1, word2):
	#lista = '''value":%s''' % lista
	#print(lista)
	#lista = {"a1": "a", "a2": "b"}
	lista = {"a1": word1 , "a2": word2}
	r = requests.post(endereco_servidor, json=lista)
	print(r.text)

def listar():
	r = requests.get(endereco_servidor)
	print(r.text)

def buscar(id):
	r = request.get(endereco_servidor+str(id))
	#print(r.json())

def apagar(id):
	r = request.delete(endereco_servidor+str(id))
	#print(r.json())

def atualizar(id, valor):
	r = requests.put(endereco_servidor, data={str(id):valor})
	#print(r.json())

if __name__ == '__main__':
	
	task = sys.argv[1]

	if task == "adicionar":
		#entrada = len(sys.argv)
		#for i in range(2,entrada):
		first_arg = sys.argv[2]
		second_arg = sys.argv[3]
		adicionar(first_arg, second_arg)

	elif task == "listar":
		listar()

	elif task == "buscar":
		buscar(sys.argv[2])

	elif task == "apagar":
		entrada = len(sys.argv[i])
		for i in range(2,entrada):
			apagar(sys.argv[i])

	elif task == "atualizar":
		print("atualizar")
		first_arg = sys.argv[2]
		second_arg = sys.argv[3]
		atualizar(first_arg)
